version: '3.9'

services:
  frontend-dev:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules # Prevents overwriting node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    
  frontend-prod:
    container_name: frontend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    command: npm run start